#!/bin/bash

# Copyright 2021 Maria P. Acosta F. macosta-at-fnal-dot-gov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Terminal utils
BL="\033[1;34m"
YL="\033[1;33m"
WHT="\033[1;97m"
CY="\033[1;36m"
MGT="\033[1;35m"
GR="\033[1;32m"
RD="\033[1;31m"
NO_COLOR="\033[0m"

# Launch a full stack CMS glidein on a set of THETA nodes
# Setting some defaults for easier debugging
export HPC_SITE=ALCF_THETA
export HPC_BATCH_SYSTEM=COBALT

export THETA_USER=macosta
export ALLOCATION=HEPCloud-FNAL
export QUEUE=debug-cache-quad

export NODE_CNT=1
export EDGE='false'
export TIME="60"
export JOB_ID=${RANDOM}

# Gathering parameters for the request
while getopts 'u:n:q:t:j:f:a:eh' flag; do
  case "${flag}" in
    u) export THETA_USER="${OPTARG}" ;;
    n) export NODE_CNT="${OPTARG}" ;;
    q) export QUEUE="${OPTARG}" ;;
    t) TIME="${OPTARG}" ;;
    j) export JOB_ID="${OPTARG}" ;;
    f) export SCHEDD_FILE="${OPTARG}" && export _minicondor_tmp_SCHEDD_FILE="$(readlink -f ${OPTARG})" ;;
    a) export ALLOCATION="${OPTARG}" ;;
    e) EDGE='true';;
    h) echo "Usage: $0"
       echo "Optional: -u [<THETA user>] -n [<Node count>] -q [<THETA queue>] -t [<Node time>] -a [<THETA allocation]>"
       echo "Required: -f [<SCHEDD job queue file]" 1>&2 ; exit 1
       ;;
  esac
done

if [ -z "${SCHEDD_FILE}" ]
then
  echo -e "${RD}# ERROR: A required parameter '-f [<SCHEDD job queue file]' was not detected"
  echo -e "${RD}# I need a lumberjack-exported job_queue.log to work properly"
  echo -e "# For insructions about the experimental export process, go to: https://github.com/HEPCloud/fnalhpc_startd/tree/master/lumberjack"
exit 1
fi 

export SLOT_PREFIX="cobalt-cms-${JOB_ID}"
export GLIDEIN_NAME="cobalt-cms-${JOB_ID}@theta.alcf.anl.gov"
export THETA_BASE_DIR="/projects/${ALLOCATION}/job_area/${SLOT_PREFIX}"
export PATH=$PATH:$(dirname "$0")/bin

echo ""
echo "====== Starting minicondor_hpc on ${HPC_SITE} (${HPC_BATCH_SYSTEM}) "
echo ""

source stage_hpc_job -s ${HPC_SITE} -b ${HPC_BATCH_SYSTEM}

echo ""
echo "====== Analyzing job_queue.log for directories needed by my jobs"
echo ""

if [ -z $EDGE ]
then
  echo ""
  echo "====== Running in "Edge" mode. Please make sure to provide a valid IDTOKEN and COLLECTOR_HOST for this "lumberjack_edge_schedd" @ ${HPC_SITE}"
  echo ""
    source stage_lumberjack_files -e
    exit 0
    source start_hpc_schedd -s ${HPC_SITE} -c ${CONTAINER_ENGINE} -p ${COLLECTOR_HOST}
    exit 0
  echo "[.....]"
  echo "====== Machine: $(hostname) reporting to HTCondor collector(s) at ${COLLECTOR_HOST}"
else
    source stage_lumberjack_files ${JOB_QUEUE}
    exit 0
fi

echo ""
echo "====== Submitting a ${HPC_BATCH_SYSTEM} job for this Lumberjack queue"
echo ""

source minicondor_submit -s ${HPC_SITE} -b ${HPC_BATCH_SYSTEM}
exit 0

